export const collection = [
  {
    id: "j-5017",
    variantId: "fa-18c",
    serialNumber: "1371/SFC017",
    currentRegistration: "J-5017",
    currentOperator: "Swiss Air Force",
    currentSquadron: "Fliegerstaffel 11",
    currentCountryIso2: "CH",
    currentStatus: "active",
    livery: "Standard low-visibility Swiss Air Force grey",
    builtYear: 1996,
    notes: "Physical airframe record with preserved lifecycle entries and sighting evidence.",
    country: { iso2: "CH", iso3: "CHE", defaultName: "Switzerland" },
    manufacturer: { id: "mcdonnell-douglas", name: "McDonnell Douglas", countryIso2: "US" },
    model: {
      id: "fa-18-hornet",
      manufacturerId: "mcdonnell-douglas",
      name: "F/A-18 Hornet",
      category: "fighter",
      introducedYear: 1983,
    },
    variant: {
      id: "fa-18c",
      modelId: "fa-18-hornet",
      name: "F/A-18C",
      role: "Multirole fighter",
      firstFlightYear: 1987,
      introducedYear: 1989,
      specs: {
        crew: 1,
        lengthM: 17.1,
        wingspanM: 12.3,
        heightM: 4.7,
        maxSpeedKmh: 1915,
        rangeKm: 2000,
        serviceCeilingM: 15000,
        engineSummary: "2x General Electric F404-GE-402 turbofans",
        radarSummary: "AN/APG-73 multimode radar",
        armamentSummary: "20 mm cannon, air-to-air missiles, precision stores",
      },
    },
    history: [
      {
        id: "j5017-delivery",
        date: "1996-12-12",
        type: "registration",
        label: "Delivered as J-5017",
        detail: "Accepted into Swiss Air Force service.",
      },
      {
        id: "j5017-sqn11",
        date: "2005-04-01",
        type: "squadron",
        label: "Assigned to Fliegerstaffel 11",
        detail: "Operational assignment at Meiringen Air Base.",
      },
      {
        id: "j5017-livery",
        date: "2018-09-14",
        type: "livery",
        label: "Low-visibility livery recorded",
        detail: "Current Swiss Air Force grey scheme confirmed.",
      },
    ],
    sightings: [
      {
        id: "j5017-axalp",
        date: "2024-10-16",
        location: "Axalp-Ebenfluh range",
        countryIso2: "CH",
        latitude: 46.7168,
        longitude: 8.04,
        event: "Axalp demonstration",
        photographer: "Collection owner",
        photoCount: 0,
      },
      {
        id: "j5017-meiringen",
        date: "2025-06-04",
        location: "Meiringen Air Base",
        countryIso2: "CH",
        latitude: 46.7433,
        longitude: 8.1092,
        photographer: "Collection owner",
        photoCount: 0,
      },
    ],
  },
  {
    id: "f-rbal",
    variantId: "a400m",
    serialNumber: "MSN033",
    currentRegistration: "F-RBAL",
    currentOperator: "French Air and Space Force",
    currentCountryIso2: "FR",
    currentStatus: "active",
    livery: "French tactical transport grey",
    builtYear: 2015,
    notes: "Transport aircraft example sharing the same normalized lifecycle model.",
    country: { iso2: "FR", iso3: "FRA", defaultName: "France" },
    manufacturer: { id: "airbus", name: "Airbus", countryIso2: "FR" },
    model: {
      id: "a400m-atlas",
      manufacturerId: "airbus",
      name: "A400M Atlas",
      category: "transport",
      introducedYear: 2013,
    },
    variant: {
      id: "a400m",
      modelId: "a400m-atlas",
      name: "A400M",
      role: "Tactical airlifter",
      firstFlightYear: 2009,
      introducedYear: 2013,
      specs: {
        crew: 3,
        maxTakeoffWeightKg: 141000,
        maxSpeedKmh: 780,
        rangeKm: 3300,
        serviceCeilingM: 11280,
        engineSummary: "4x Europrop TP400-D6 turboprops",
        radarSummary: "Weather and terrain awareness avionics suite",
        armamentSummary: "Unarmed transport platform",
      },
    },
    history: [
      {
        id: "frbal-delivery",
        date: "2015-07-03",
        type: "registration",
        label: "Delivered as F-RBAL",
        detail: "Assigned to French transport fleet.",
      },
      {
        id: "frbal-operator",
        date: "2015-07-04",
        type: "operator",
        label: "Operator confirmed",
        detail: "French Air and Space Force recorded as current operator.",
      },
    ],
    sightings: [
      {
        id: "frbal-payerne",
        date: "2024-09-07",
        location: "Payerne Air Base",
        countryIso2: "CH",
        latitude: 46.8432,
        longitude: 6.9151,
        event: "Airshow static display",
        photographer: "Collection owner",
        photoCount: 0,
      },
    ],
  },
];
